config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get '/pages/:permalink' => 'pages#permalink', as: "permalink"
  get '/search', to: 'search#index'
  resources :products
  resources :search
  resources :abouts, only: %i[index new edit ]
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
    validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :product_stock, :price, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: %i[show edit update destroy]

  # GET /abouts or /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1 or /abouts/1.json
  def show; end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit; end

  # POST /abouts or /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to about_url(@about), notice: "About was successfully created." }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1 or /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to about_url(@about), notice: "About was successfully updated." }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1 or /abouts/1.json
  def destroy
    @about.destroy

    respond_to do |format|
      format.html { redirect_to abouts_url, notice: "About was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_about
    @about = About.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def about_params
    params.fetch(:about, {})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages

  def cms_pages
    Page.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.take(30)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  http_basic_authenticate_with name: "admin", password: "secret", except: [:show]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :content, :permalink)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully created."
        end
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to product_url(@product), notice: "Product was successfully updated."
        end
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :product_stock)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @products2 = Product.all

    @search = params["search"]
    if @search.present?
        @name = @search["name"]
        @products2 = Product.where("name LIKE ?", "%#{@name}%")
    end
  end
  scope module: "product" do
    resources :search
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/abouts/_form.html.erb
<%= simple_form_for(@about) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>About</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= link_to 'Show', about %></td>
        <td><%= link_to 'Edit', edit_about_path(about) %></td>
        <td><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New About', new_about_path %>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/home/_top_products.html.erb

  <h2 class="title is-2"><%= link_to product.name %></h2>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= product.price %>
</p>

<p>
  <strong>Product stock:</strong>
  <%= product.product_stock %>
</p>

<%= link_to 'Edit', edit_product_path(product) %> |
<%= link_to 'Back', products_path %>

<hr>

app/views/home/index.html.erb
<hr>
<%= render partial: @products, locals: {show_link: true}%>
<br>

app/views/layouts/_menu.html.erb
<!DOCTYPE html>
<div class="menu">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #DDEDDD;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Le Shoppe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
       <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", abouts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/privacy">Privacy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Login</a>
        </li>
        </ul>
    </div>
      <form class="form-inline" style="display: flex; margin: 5px;  width: 500px;">
        <%= simple_form_for :search, url: search_path, method: "GET", html: { class: 'form-inline' } do |f| %>
      <p style=" width: 400px;"><%= f.input :name, label: false %></p>
      <p style= "margin: 0px 5px;"><%= f.submit "Search", class: "btn btn-outline-success" %></p>
    <% end %>
        <%= button_to "Clear Search", products_path, class: "btn btn-outline-success", method: :get %>
  </form>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " - " if content_for?(:html_title) %> le shoppe </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: "layouts/menu" %>

    <%= yield %>
  </body>
  <hr>
  <footer style= "display:flex; justify-content: space-between;">
    <%= link_to "Home", root_path, class: "nav-link" %>
    <%= link_to "Products", products_path, class: "nav-link" %>
    <% cms_pages.each do |page| %>
    <%= link_to page.title, permalink_path(page.permalink) %>
    <% end %>
    <p style="text-align:center" >le shoppe © copywrong 2021 - built by Mike </p>
  </footer>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :permalink %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table class ="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', permalink_path(page.permalink), class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: "btn btn-warning"%></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h2 class="">New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :product_stock %>
    <%= form.text_field :product_stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb

<% if(show_link) %>
  <h2 class="title is-2"><%= link_to product.name, product %></h2>
<% else %>
  <%= product.name%>
<% end %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= product.price %>
</p>

<p>
  <strong>Product stock:</strong>
  <%= product.product_stock %>
</p>

<%= link_to 'Edit', edit_product_path(product) %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%= render partial: @products, locals: {show_link: true}%>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% content_for(:html_title) { @product.name }%>

<%= render partial: @product, locals: {show_link: false} %>

<hr>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>


<div class="container">
<table class="table-secondary">
  <tbody>
      <div class="col-xs-12 col-sm-5 offset-sm-2">
        <% @products2.each do |b2| %>
          <tr class="table-primary">
            <td class="table-light"><%= link_to b2.name, b2 %></td>
          </tr>
        <% end %>
      </div>
    </div>
  </tbody>
</table>
</div>